SOURCES :=								\
	LICENSE.txt							\
	README.md							\
	requirements.txt						\
	youpy/__init__.py						\
	youpy/__main__.py						\
	youpy/api.py							\
	youpy/cli/__init__.py						\
	youpy/cli/argparse.py						\
	youpy/code/__init__.py						\
	youpy/code/english/__init__.py					\
	youpy/code/english/control.py					\
	youpy/code/english/everything.py				\
	youpy/code/english/looks.py					\
	youpy/code/english/motion.py					\
	youpy/code/english/sensing.py					\
	youpy/code/english/variable.py					\
	youpy/command/__init__.py					\
	youpy/command/run.py						\
	youpy/concurrency.py						\
	youpy/configurer.py						\
	youpy/coordsys.py						\
	youpy/data.py							\
	youpy/engine.py							\
	youpy/error.py							\
	youpy/event.py							\
	youpy/examples/SimpleBasketBall.sb3				\
	youpy/examples/SimpleBasketBall/.youpy/config.json		\
	youpy/examples/SimpleBasketBall/BasketBall/BasketBall.png	\
	youpy/examples/SimpleBasketBall/BasketBall/BasketBall.py	\
	youpy/examples/SimpleBasketBall/BasketBall/__init__.py		\
	youpy/examples/SimpleBasketBall/Hand/Hand.png			\
	youpy/examples/SimpleBasketBall/Hand/Hand.py			\
	youpy/examples/SimpleBasketBall/Hand/__init__.py		\
	youpy/examples/SimpleBasketBall/LICENSE.txt			\
	youpy/examples/SimpleBasketBall/__init__.py			\
	youpy/examples/SimpleBasketBall/__main__.py			\
	youpy/examples/SimpleBasketBall/stage/GameOver.png		\
	youpy/examples/SimpleBasketBall/stage/InGame.png		\
	youpy/examples/SimpleBasketBall/stage/Welcome.png		\
	youpy/examples/SimpleBasketBall/stage/__init__.py		\
	youpy/examples/SimpleBasketBall/stage/stage.py			\
	youpy/examples/__init__.py					\
	youpy/keys.py							\
	youpy/loader.py							\
	youpy/logging.py						\
	youpy/loop.py							\
	youpy/math.py							\
	youpy/message.py						\
	youpy/project.py						\
	youpy/runner.py							\
	youpy/script.py							\
	youpy/test/__init__.py						\
	youpy/test/test_coordsys.py					\
	youpy/test/test_event.py					\
	youpy/tools.py

GENERATED_SOURCES := $(VERSION_FILE)
